name: Playground

on:
  workflow_dispatch:
      version:
        description: If provided, the version will be appended to the title
        required: false

permissions:
  contents: write

jobs:
  publish:
    name: Publish the documentation

    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: Generate Zoomin tags.yml
        env:
          ZOOMIN_DOCS_VERSION: ${{ github.event.inputs.version }}
        run: |
          cd ${{ env.DOWNLOAD_DIR }}

          echo "# Document tags for Zoomin.

          # Tags for all topics:
          mapping_global:
            - nrf-asset-tracker
            - nrf-asset-tracker-$ZOOMIN_DOCS_VERSION

          # Tags for individual topics:
          mapping_topics:
            - docs/*.html: [\"applications\"]
            - docs/*/*.html: [\"applications\"]
            - docs/*/*/*.html: [\"applications\"]" > tags.yml

          echo "tags.yml"
          cat tags.yml

      - name: Add custom.properties and zip
        env:
          ZOOMIN_TITLE: ${{ vars.ZOOMIN_TITLE || 'nrf-asset-tracker' }}
          ZOOMIN_BOOK_TITLE:
            ${{ vars.ZOOMIN_BOOK_TITLE || 'nRF Asset Tracker' }}
          ZOOMIN_DOCS_VERSION: ${{ github.event.inputs.version }}
        run: |
          [[ -n "$ZOOMIN_DOCS_VERSION" ]] && ZOOMIN_TITLE="${ZOOMIN_TITLE}-${ZOOMIN_DOCS_VERSION}"
          [[ -n "$ZOOMIN_DOCS_VERSION" ]] && ZOOMIN_BOOK_TITLE="${ZOOMIN_BOOK_TITLE} ${ZOOMIN_DOCS_VERSION}"
          NORMALIZED_ZOOMIN_TITLE=${ZOOMIN_TITLE// /_}

          cd ${{ env.DOWNLOAD_DIR }}
          touch custom.properties
          echo "manual.name=${NORMALIZED_ZOOMIN_TITLE}" >> custom.properties
          echo "booktitle=${ZOOMIN_BOOK_TITLE}" >> custom.properties

          echo "custom.properties"
          cat custom.properties
