name: Playground zoomin

on:
  workflow_dispatch:
  push:
    branches:
      - zoomin

permissions:
  contents: write
  actions: write

jobs:
  build:
    name: "Build the documentation"
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - uses: actions/upload-artifact@v3
        with:
          if-no-files-found: error
          name: asset-tracker-docs-${{ github.sha }}
          path: build/html/

      - name: Trigger publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh workflow run publish-docs-zoomin.yaml --field github_sha=${{ github.sha }} --field repo=${{ github.repository }} --field ref=${{ github.ref }}

